### PR TITLE
Rf 265 Directory restructure

### LINKED ISSUE #265: [Refactor]: Directory Restructuring
### Refactor Request

```
.
├── App.tsx
├── components
│   ├── Button
│   │   ├── index.tsx
│   │   └── style.scss
│   └── index.tsx
├── pages
│   ├── HomePage
│   │   ├── index.tsx
│   │   └── style.scss
│   ├── index.tsx
│   └── JoinPage
│       ├── index.tsx
│       └── style.scss
└── style.scss
```

### Describe the proposed solution

_No response_

### PR DESCRIPTION
**Pull request by Njima1572**
## Which Issue was this PR made for?

- Closes #265 

## What is within the scope with this PR

- Changing directory structure
- Resolving import issues that will be caused by this

## Other sidenotes that reviewer should be aware of
- Left atomize_wrapper as is, since it is like its own thing. Will solve this in different issue
- Also this PR is based on #262 branch

### CODE REVIEW

**Review by siberowl — COMMENTED** [review]
I think AvatarDOM should be in its own folder as well for consistency.
I'm thinking like AvatarCanvas/AvatarDOM/index.tsx

Also, I personally think the directory names should follow a kebab-case style (keep camel cases for class/component names) for readability

**Comment by Njima1572** [comment]
> Also, I personally think the directory names should follow a kebab-case style (keep camel cases for class/component names) for readability

I agree. Were there any that needs to be changed for this?

**Comment by siberowl** [comment]
> > Also, I personally think the directory names should follow a kebab-case style (keep camel cases for class/component names) for readability
> 
> I agree. Were there any that needs to be changed for this?

I was thinking like:
AvatarCanvas -> avatar-canvas
AvatarDOM -> avatar-dom
ButtonsBar -> buttons-bar
etc.

**Review by siberowl — CHANGES_REQUESTED** [review]
Changing directory names to kebab-style? (open to opinions)

**Comment by Njima1572** [comment]
For the directory names, I want to keep it the way it is. At least for the component ones.

https://github.com/airbnb/javascript

Selection_370

**Comment by siberowl** [comment]
> For the directory names, I want to keep it the way airbnb style says. Keep the directory name same as the default export component name
> 
> https://github.com/airbnb/javascript
> 
> Selection_370
> 
> 

Sounds good that's fine with me👍

**Review by siberowl — APPROVED** [review]
LGTM

**Pull request merged**
