### PR TITLE
bg-263 Removed profile part of docker-compose

### LINKED ISSUE #263: [Bug]: Test runs on dev-up
### Expected Behaviour

Test should not be running

### Actual Behaviour

Test runs

### How to Reproduce the problem

make dev-up

### Additional Info

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Njima1572**
## Which Issue was this PR made for?

- Closes #263  

## What is within the scope with this PR

- Removing the profile part of docker-compose (I believe this also makes it compatible with docker-compose 1.25

### CODE REVIEW

**Review by siberowl — CHANGES_REQUESTED** [review]
I never noticed the tests running on main. Was it running silently?
image

**Comment by Njima1572** [comment]
Huh, then maybe I was the only one having that issue??

**Comment by Njima1572** [comment]
Selection_365

**Review by siberowl — APPROVED** [review]
Looks fine to me

**Pull request merged**
