### PR TITLE
Ft-283 Added simple visual test

### LINKED ISSUE #283: [Feature]: Implement simple visual tests
### What feature?

Implement tests to make sure things load as expected to prevent bugs like
- #281

### PR DESCRIPTION
**Pull request by Njima1572**
## Which Issue was this PR made for?

- Closes #283 

## What is within the scope with this PR

- [x] `make test` to run test
- [x] `make test-headed` to run it with running a chromium
- [x] Simple client side test without server
  - [x] Enter `test` for roomname and click create
  - [x] Enter `test` for username and click join
  - [x] Leave room 

## What is NOT in the scope with this PR
- Different browser testing
- Testing with server

## Other sidenotes that reviewer should be aware of

I only ran it on linux, not sure how it works with WSL @siberowl

### CODE REVIEW

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-300.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-300.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-300.dev.mochatto.com

**Review by siberowl — APPROVED** [review]
Not totally sure how to make the headed work on wsl yet, but looks good as a preliminary test file.
Will want to make folders for unit/integration/acceptance (this one falls in here) and make filters to specify which test to run in the future

**Pull request merged**
