### PR TITLE
rf-321 - Created Shared folder between server and client

### LINKED ISSUE #321: [Refactor]: Create a shared folder between client and server
### Refactor Request

Make types / methods in sync with frondend and backend,

### Describe the proposed solution

I was thinking of creating a folder called `shared` at the root of the project and have hard links to the files in this in both frontend and backend.

- [ ] Some of the types
- [x] SocketIO channel name enum
- [x] Authentication response code
- [ ] Hash functions (if possible)

### PR DESCRIPTION
**Pull request by Njima1572**
## Which Issue was this PR made for?

- Closes #321 

## What is within the scope with this PR

- [x] Create shared folder with shared items
- [x] Do whatever needed to be done to make dev-up / prod-up to work

## Other sidenotes that reviewer should be aware of

- This does create diff to both server / client file.
- Doesn't work as expected with freshly cloned repo

### CODE REVIEW

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-337.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-337.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-337.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-337.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-337.dev.mochatto.com

**Comment by Njima1572** [comment]
I'll try creating pre-run script and pre-build script.

**Comment by Njima1572** [comment]
Having problem dealing with soft link with tsc / lsps

**Review by siberowl — APPROVED** [review]
This is awesome thanks!!

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-337.dev.mochatto.com

**Pull request merged**
