### PR TITLE
Debug 122

### LINKED ISSUE #122: [Bug]: Crashes when new user joins the room
### Expected Behaviour

Be able to have actual screen

### Actual Behaviour

Turns into blank screen

### Additional Info

Set default values???

### Relevant log output

```shell
TypeError: n.avatarColor is undefined
    children AvatarCanvas.tsx:80
    W AvatarCanvas.tsx:68
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    j PositionsContext.tsx:36
    value User.ts:120
    ondatachannel RTCPeerConnector.ts:113
react-dom.production.min.js:216:199
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    j PositionsContext.tsx:36
    value User.ts:120
    ondatachannel RTCPeerConnector.ts:113



Uncaught TypeError: n.avatarColor is undefined
    children AvatarCanvas.tsx:80
    W AvatarCanvas.tsx:68
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    j PositionsContext.tsx:36
    value User.ts:120
    ondatachannel RTCPeerConnector.ts:113
AvatarCanvas.tsx:80:12
```

### PR DESCRIPTION
**Pull request by Njima1572**
## Which Issue was this PR made for?

- Closes #122

### CODE REVIEW

**Comment by siberowl** [comment]
Doesn't fix the root issue so I'd rather now merge this into main. Also, keeping the DeviceSelector mounted doesn't fix the issue where the selected audio device in JoinPage doesn't reflect what gets selected when RoomPage loads.

I like the type fixing in UserInfoContext though.

**Review by siberowl — CHANGES_REQUESTED** [review]
Doesn't fix the root issue so I'd rather now merge this into main. Also, keeping the DeviceSelector mounted doesn't fix the issue where the selected audio device in JoinPage doesn't reflect what gets selected when RoomPage loads.

I like the type fixing in UserInfoContext though so maybe only that.

I'd like to fix all the bugs in separate branches, merge them into a single debug branch and then merge into main.

**Comment by siberowl** [comment]
Fixed the audio device issue in so can revert the permanent mount change:
- #128

Instead of handling this error here:
https://github.com/Amijakan/mochatto/blob/ac7828db3e1a7eed8659f3b21830c08ff827e035/client/src/components/AvatarCanvas.tsx#L81-L82

Let's handle it within UserInfoContext:
https://github.com/Amijakan/mochatto/blob/ac7828db3e1a7eed8659f3b21830c08ff827e035/client/src/contexts/UserInfoContext.tsx#L31-L38

Have a check to see if all the elements of a UserInfo exists in newInfo, and add it in if it doesn't.

**Comment by siberowl** [comment]
Also, this PR should merge into bugs-123 instead of main.

**Comment by Njima1572** [comment]
Something more like a git flow kind of usage

**Review by siberowl — APPROVED** [review]

**Review by siberowl — APPROVED** [review]

**Pull request merged**
