### PR TITLE
ft-232 Updated jenkinsfile trigger

### LINKED ISSUE #232: [Feature] Use Jenkins to deploy to `mochatto.com` on push to main
- [ ] The build process fires when main branch gets a commit
- [x] Nice to have: see the result in github with green tick or red x

## Concerns
1. There needs to be some kind of verification that it is a functioning build. (like test / beta branch human confirmation)

## Steps
- [x] #285
- [ ] Create a job that updates main, when main gets a new commit
- [x] Create a job that creates subdomain.mochatto.com for each pr when pr is created
  - [x] Remove when PR is merged
  - [x] Nice to have: Comment the url when the build is done

### PR DESCRIPTION
**Pull request by Njima1572**
- Closes #232 

Still not sure how it performs on main branch

-  [x] Creates a https://pr-{number}.dev.mochatto.com on pull request
- [x] Comments the url to pr
-  [x] Stops the container when the pr is merged

## Other notes

Moved `nginx` file to client folder, bc mounting does not work well when creating a sibling docker container. (Path in host and path in container that is calling new container differs)

### CODE REVIEW

**Comment by Njima1572** [comment]
Deployed to https://PR-288.dev.mochatto.com

**Comment by Njima1572** [comment]
Deployed to https://pr-288.dev.mochatto.com

**Comment by Njima1572** [comment]
Deployed to https://pr-288.dev.mochatto.com

**Comment by Njima1572** [comment]
Deployed to https://pr-288.dev.mochatto.com

**Comment by Njima1572** [comment]
Deployed to https://pr-288.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-288.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-288.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-288.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-288.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-288.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-288.dev.mochatto.com

**Review by siberowl — APPROVED** [review]
LGTM

**Pull request merged**
