### PR TITLE
bg-303 fixed typeface

### LINKED ISSUE #303: [Bug]: Fix typeface
### Expected Behaviour

Font should not be helvetica

### Actual Behaviour

Font is helvetica

### How to Reproduce the problem

_No response_

### Additional Info

image

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by siberowl**
## Which Issue was this PR made for?

- Closes #303

## What is within the scope with this PR
Fixed this:
image

to:
image

### CODE REVIEW

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-304.dev.mochatto.com

**Comment by Njima1572** [comment]
AUTOMATED: Deployed to https://pr-304.dev.mochatto.com

**Comment by Njima1572** [comment]
Wouldn't it be better to specify a font explicitly? like to `sans-serif`

**Comment by siberowl** [comment]
> Wouldn't it be better to specify a font explicitly? like to `sans-serif`

There's already a global font-family assigned here:
https://github.com/Amijakan/mochatto/blob/9dab28620c834b6568a9fb5c6297e88831c345da/client/src/index.css#L5

**Review by Njima1572 — APPROVED** [review]
LGTM

**Pull request merged**
