### PR TITLE
Bug 158

### LINKED ISSUE #158: [Bug]: App crashes when there is no audio input
### Expected Behaviour

Even if no microphone is detected, the users should be able to move around and listen to people

### Actual Behaviour

Crashed.

### Additional Info

It happens when you need to send your info to the other party.

Selection_105

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by siberowl**
## Which Issue was this PR made for?

- Closes #158 

## What is within the scope with this PR

- #158

### CODE REVIEW

**Comment by Njima1572** [comment]
Selection_114

New bug

**Comment by siberowl** [comment]
> Selection_114
> 
> New bug
How do I reproduce this?

**Comment by Njima1572** [comment]
> How do I reproduce this?

Tryin

**Comment by Njima1572** [comment]
https://user-images.githubusercontent.com/9146455/134542025-93a8b880-dfe2-49d6-9844-9eb929bbdac3.mp4

**Comment by Njima1572** [comment]
LGTM

**Pull request merged**
